name: Deploy Backend

on:
  push:
    branches:
      - release/production
    paths:
      - Backend/**

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Deploy CloudFormation Stack
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd Backend
          aws cloudformation deploy \
            --template-file cfn-template.yaml \
            --stack-name Password-Crud-Application-Stack \
            --capabilities CAPABILITY_IAM
