name: Deploy Backend

on:
  push:
    paths:
      - Backend/**

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy CloudFormation Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          cd Backend
          aws cloudformation deploy \
            --template-file cfn-template.yaml \
            --stack-name MyBackendStack \
            --capabilities CAPABILITY_IAM
